apiVersion: v1
kind: Service
metadata:
  name: resource-broker
  namespace: resource-broker
  labels:
    app.kubernetes.io/name: resource-broker
    app.kubernetes.io/component: controller
spec:
  ports:
    - port: 443
      targetPort: 8080
      name: https
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: resource-broker
